version: '3.8'
services:
  selenium-chrome:
    image: selenium/standalone-chrome:4.0.0
    ports:
      - "4444:4444"
    networks:
      - app-network

  flask-app:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - selenium-chrome
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
